### ISSUE TITLE
LTXVLoaderMultiGPU and CLIPLoaderGGUFMultiGPU not appear

### ISSUE THREAD

**Issue by x4080** [pollockjj/ComfyUI-MultiGPU#3]
Hi, other default MultiGPU appears, but these two that I wanted to use not available (already installed LTXV and GGUF), I dont know what I did wrong, but I install it using git clone, is there any difference between git clone and comfyui manager ?

Edit: Using comfy manager to install it and the node still missing

**Comment by pollockjj** [comment]
I would attempt to refresh your nodes / reboot your Comfy nodes if you haven't already? If you'd like, send me your workflow, perhaps I can send you back one with those in place?
<img width="388" alt="image" src="https://github.com/user-attachments/assets/bbbc55f9-c996-41fd-aa6e-3d6fa9a56876" />

**Comment by x4080** [comment]
@pollockjj Thanks, I tried many times dont know why it wont appear, tried your example workflows also but not appear, here's my workflow if you dont mind

[ltxv_image_to_video gguf.json](https://github.com/user-attachments/files/18247227/ltxv_image_to_video.gguf.json)

**Comment by x4080** [comment]
<img width="900" alt="Screenshot 2024-12-26 at 04 45 52" src="https://github.com/user-attachments/assets/007779e9-6130-4b05-b5d8-71c580540b83" />

I tried it again and got the screenshot, as you can see I have GGUF node available but the muliGPU nodes are only the default ones

**Comment by mitchross** [comment]
same issue here 

![image](https://github.com/user-attachments/assets/54adf997-5b2d-411d-b2c1-91adb1f16cde)

**Comment by pollockjj** [comment]
OK, two of you, with slightly different problems.

Can each of you do the following?:

1. Update your ComfyUI install, make sure it is at the latest. Using ComfyManager, 
2. <img width="802" alt="image" src="https://github.com/user-attachments/assets/86159ec4-84bb-40cc-841c-96abd28363e4" />
3. Once that is complete (it might take some time) it will ask you to restart. Please do so.
4. In a new browser tab (ideally a fresh browser of an incognito tab) load up you workflow in comfy ui.
5. Attempt to locate the nodes.
6. If the nodes are not found, please send me a copy of "comfyui.log" which should contain only information since the last reboot which might help me pin down your problem.

**Comment by x4080** [comment]
@pollockjj Thanks, I tried it and still GGUFMultiGPU is not available like before, but dont worry about it

**Comment by pollockjj** [comment]
One thing I would mention is that MultiGPU _extends_ existing custom_nodes' functionality. It does not add any of the existing custom_nodes that it relies on:

From the README.md:

<img width="608" alt="image" src="https://github.com/user-attachments/assets/9af19401-a82e-4303-bd91-414ffe6f1343" />

Please install any missing custom_nodes that MultiGPU relies upon to function and let me know if that fixes your issue.

**Comment by x4080** [comment]
@pollockjj As I attached before, I already installed the ComfyUI GGUF.

**Comment by pollockjj** [comment]
@x4080 - then please provide me with your logfile and a screenshot of your loading screen so I can further debug. Those are the only avenues I can see to making progress with your issue.

Thanks.

**Comment by pollockjj** [comment]
@x4080,p lease try the new version from the dev branch here (just replace __init__.py in ComfyUI/custom_nodes/ComfyUI-MultiGPU with the one I am linking here:

https://github.com/pollockjj/ComfyUI-MultiGPU/blob/dev/__init__.py

This changes the loading to be deterministic. I also put in a bunch of logging so we can see more of what is going on if this doesn't fix your issue.

Thanks!

**Comment by x4080** [comment]
@pollockjj Thanks for your effort, I'll try it later

**Comment by Trojaner** [comment]
I am having the same issue.

![image](https://github.com/user-attachments/assets/0e607edd-dfe7-4799-98c6-2b9909d60e91)

```
MultiGPU: Initialization started
MultiGPU: Initial device cuda:0
MultiGPU: Starting core node registration
MultiGPU: Registered core node UNETLoader
MultiGPU: Registered core node VAELoader
MultiGPU: Registered core node CLIPLoader
MultiGPU: Registered core node DualCLIPLoader
MultiGPU: Registered core node TripleCLIPLoader
MultiGPU: Registered core node CheckpointLoaderSimple
MultiGPU: Registered core node ControlNetLoader
MultiGPU: Checking for module at custom_nodes/ComfyUI-GGUF/__init__.py
MultiGPU: Module ComfyUI-GGUF not found - skipping
MultiGPU: Checking for module at custom_nodes/x-flux-comfyui/__init__.py
MultiGPU: Module x-flux-comfyui not found - skipping
MultiGPU: Checking for module at custom_nodes/ComfyUI-Florence2/__init__.py
MultiGPU: Module ComfyUI-Florence2 not found - skipping
MultiGPU: Checking for module at custom_nodes/ComfyUI-LTXVideo/__init__.py
MultiGPU: Found ComfyUI-LTXVideo, attempting to load
MultiGPU: Error processing ComfyUI-LTXVideo: No module named 'ComfyUI-LTXVideo'
MultiGPU: Checking for module at custom_nodes/ComfyUI-MMAudio/__init__.py
MultiGPU: Module ComfyUI-MMAudio not found - skipping
MultiGPU: Checking for module at custom_nodes/ComfyUI_bitsandbytes_NF4/__init__.py
MultiGPU: Module ComfyUI_bitsandbytes_NF4 not found - skipping
MultiGPU: Registration complete. Final mappings: UNETLoaderMultiGPU, VAELoaderMultiGPU, CLIPLoaderMultiGPU, DualCLIPLoaderMultiGPU, TripleCLIPLoaderMultiGPU, CheckpointLoaderSimpleMultiGPU, ControlNetLoaderMultiGPU
Nvidia APEX normalization not installed, using PyTorch LayerNorm
```

**Comment by pollockjj** [comment]
Hello, @Trojaner, @mitchross, and @x4080 

I believe I have implemented a robust method to address your issues in my latest commit. 

If you could please update to the latest version I believe you will find your issues fixed.

Thank your for your patience.

**Comment by Trojaner** [comment]
@pollockjj thank you for looking into this.
I have tested with with latest dev and main branches, unfortunately the issue persists.
> MultiGPU: Error processing ComfyUI-LTXVideo: No module named 'ComfyUI-LTXVideo'

**Comment by x4080** [comment]
@Trojaner @pollockjj Thats a good start

**Comment by pollockjj** [comment]
So, still working on the LTXLoader issue. I pushed a small update for a bit more logging if you would be so kind as collect that on your next run.

I am committed to getting this working. That said, if this is preventing you from trying out MultiGPU with LTXVideo, I just want to make sure you know that the standard LoadCheckpointSimpleMultiGPU works, like in the florence2_flux1dev_ltxv_cpu_2gpu.json example. 

Just trying to solve your problem a different way, since I know all the core nodes are loading flawlessly for everyone.

<img width="637" alt="image" src="https://github.com/user-attachments/assets/041b63a4-b497-48f1-853b-4d4628b7e3a9" />

I am of course continuing to troubleshoot the custom LTX loader side as well. The latest update to MultiGPU logging should hopefully shed some light one why it fails even though we are directly executing its code and interrogating its dict.

If you can, please try another time with the updated MultiGPU.

**Comment by Trojaner** [comment]
I just noticed that ComfyUI-Florence2 also does not work.

Here are your requested logs.
```
MultiGPU: Found ComfyUI-Florence2, attempting to load
MultiGPU: Failed to execute ComfyUI-Florence2: No module named 'ComfyUI-Florence2'
MultiGPU: Failed module code:
from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
MultiGPU: Error processing ComfyUI-Florence2: No module named 'ComfyUI-Florence2'
MultiGPU: Checking for module at custom_nodes/ComfyUI-LTXVideo/__init__.py
MultiGPU: Found ComfyUI-LTXVideo, attempting to load
MultiGPU: Failed to execute ComfyUI-LTXVideo: No module named 'ComfyUI-LTXVideo'
MultiGPU: Failed module code:
from .loader_node import LTXVLoader  # noqa: F401
from .nodes_registry import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .stg import LTXVApplySTG, STGGuiderNode  # noqa: F401
from .t5_encoder import LTXVCLIPModelLoader  # noqa: F401
from .transformer import LTXVModelConfigurator, LTXVShiftSigmas  # noqa: F401

# Export so that ComfyUI can pick them up.
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

MultiGPU: Error processing ComfyUI-LTXVideo: No module named 'ComfyUI-LTXVideo'
```

**Comment by Trojaner** [comment]
Update: 

I added the following log before `spec.loader.exec_module(module)`:
```python
        import sys
        for module in sys.modules:
            if "florence" in module.lower():
                logging.info(f"MultiGPU: Florence found: {module}") 
        
```

This is never logged, so I assume the main issue here is that this extension is simply loaded before the other ones.

**Comment by Trojaner** [comment]
Updated Florence __init__.py like this:
```python
from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

print("----- FLORENCE LOADED -----")
```
This is indeed logged *after* ComfyUI-MultiGPU has loaded

**Comment by pollockjj** [comment]
I appreciate the digging in!  

It _should_ not matter if the actual custom_node loads after MultiGPU (but based on the evidence you provided, this appears to be false). The code in MultiGPU is designed to take any targeted node, regardless of where it is in load order, and execute its __init__.py and grab the data real-time from the  executing that __init__.py.

That is what this code block does inside MultiGPU:

```
        try:
            spec.loader.exec_module(module)
            logging.info(f"MultiGPU: Executed {module_path} initialization")
        except Exception as exec_error:
            logging.error(f"MultiGPU: Failed to execute {module_path}: {exec_error}")
            if hasattr(module, '__file__') and os.path.isfile(module.__file__):
                with open(module.__file__, 'r', encoding='utf-8') as f:
                    logging.error(f"MultiGPU: Failed module code:\n{f.read()}")
            raise
```
            
`spec.loader.exec_module(module)` in this instance attempts to execute the entirety of the custom_node's __init__.py which should mean all of their nodes are being populated in a local NODE_CLASS_MAPPINGS dictionary I then interrogate with MultiGPU. Thus, making the custom_node's actual load order irrelevant as I run it locally inside MultiGPU.

```
        local_map_name = "NODE_CLASS_MAPPINGS"
        local_map = getattr(module, local_map_name, None)
        if not local_map:
            logging.info(f"MultiGPU: {module_path} has no '{local_map_name}' dictionary, skipping override.")
            return
```

This relies on the idempotent nature of running `__init__.py` for any custom nodes. But, as I understand it, they should all be able to be executed multiple times without changing the result.

That said, obviously I am getting something wrong or we wouldn't be here. But it isn't for lack of trying and I sincerely appreciate the ongoing effort on your part to help resolve this.

It is once again pointing that how things load  in your system prevents the code from executing in such a way as to grab it automatically.

The final solution is to hard-code the nodes in MultiGPU and then deal with the ongoing maintenance issues when nodes change.

Next on my list after this is to get a fully-hard-coded version. Which should serve as the book-end for future debugging (and to be put online until a more automated solution can be found.)

You sticking with this is greatly appreciated.

I will provide you with hard-coded Florence and LTX Multi-GPU nodes in the next iteration.

**Comment by pollockjj** [comment]
@Trojaner 

Could you please try this code from the dev branch?

https://github.com/pollockjj/ComfyUI-MultiGPU/blob/dev/__init__.py

I hard code inputs and outputs (easy, knowable) and then clone the insides at run-time, ensuring the nodes have already been registered and contain the needed info for the underlying (long, detailed, reliant on dependencies) node structure.

Please, give this one a try. If the custom_note `__init__.py` exists, it will register the nodes and you should have the desired functionality.

**Comment by Trojaner** [comment]
Both are working now 👍

**Comment by pollockjj** [comment]
The most recent refactoring of MultiGPU should eliminate any remaining missing or non-loading nodes. All nodes are manually constructed to be correct at runtime.

@Trojaner , can you move back to :main: and let me know if your problem stays resolved?

Thanks.

**Comment by pollockjj** [comment]
@x4080,

Just checking in to see if the latest version available in ComfyUI Manager is functioning correctly on your install.

The core MultiGPU code now has zero dependencies on executing code outside of MultiGPU, so I am hopeful that those on this thread experiencing issues have now found that all nodes load as expected, as long as you have the parent custom_nodes installed.

If I don't hear of any additional difficulties, I will close this ticket in a few days.

**Comment by x4080** [comment]
@pollockjj Havent been trying it again but I believe it works since other users tested it, I'll close it for now, thanks for your hard work
